language: objective-c
osx_image: xcode9

env:
  - ACTION=test  PLATFORM=iOS     DESTINATION='platform=iOS Simulator,name=iPhone 6S'

script:
  - set -o pipefail && xcodebuild -scheme StackOverflow -destination "$DESTINATION" $ACTION | xcpretty
