language: objective-c
osx_image: xcode9

script:
  - set -o pipefail && xcodebuild -workspace StackOverflow.xcworkspace -scheme StackOverflow -platform='iOS Simulator' -ios_version='10.3.1' -ios_device='iPhone SE' | xcpretty
