language: objective-c
osx_image: xcode7.3

env:
  global:
    - LANG=en_US.UTF-8

script: set -o pipefail && xcodebuild test -workspace StackOverflow.xcworkspace -scheme StackOverflow -sdk iphonesimulator9.3 | xcpretty
